import { CaseData } from "./types";

export const MOCK_CASES: Record<string, CaseData> = {
  "CASE-A": {
    caseId: "CASE-A",
    beneficiaryName: "Ahmed Al Mansoori",
    beneficiaryId: "BEN-784-001",
    emiratesId: "784-1985-1234567-8",
    loanId: "LOAN-2023-001",
    monthlyIncome: 18000,
    financialObligations: 6000,
    familyMembers: 5,
    originalLoanAmount: 800000,
    remainingLoanBalance: 612000,
    arrearsAmount: 40000,
    unpaidInstallments: 8,
    currentInstallment: 2900,
    remainingRepaymentMonths: 96,
    paymentHistory: "Mostly Regular",
    activeRequest: false,
    salaryCertificateAmount: 18000,
    salaryCertificateExpired: false,
    documentConfidence: 94,
    hasCompanyLetterhead: true,
    hasAuthorizedSignature: true,
    employeeDetailsMatch: true,
    averageSalaryTransfer6Months: 18000,
    hasMedicalDocument: false,
  },
  "CASE-B": {
    caseId: "CASE-B",
    beneficiaryName: "Mariam Al Nuaimi",
    beneficiaryId: "BEN-784-002",
    emiratesId: "784-1990-7654321-2",
    loanId: "LOAN-2022-014",
    monthlyIncome: 18000,
    financialObligations: 7000,
    familyMembers: 4,
    originalLoanAmount: 750000,
    remainingLoanBalance: 580000,
    arrearsAmount: 28000,
    unpaidInstallments: 5,
    currentInstallment: 2600,
    remainingRepaymentMonths: 72,
    paymentHistory: "Irregular",
    activeRequest: false,
    salaryCertificateAmount: 12000,
    salaryCertificateExpired: true,
    documentConfidence: 72,
    hasCompanyLetterhead: true,
    hasAuthorizedSignature: false,
    employeeDetailsMatch: true,
    averageSalaryTransfer6Months: 11000,
    hasMedicalDocument: false,
  },
  "CASE-C": {
    caseId: "CASE-C",
    beneficiaryName: "Saeed Al Ketbi",
    beneficiaryId: "BEN-784-003",
    emiratesId: "784-1978-9876543-4",
    loanId: "LOAN-2021-022",
    monthlyIncome: 16000,
    financialObligations: 11000,
    familyMembers: 6,
    originalLoanAmount: 680000,
    remainingLoanBalance: 505000,
    arrearsAmount: 25000,
    unpaidInstallments: 4,
    currentInstallment: 2800,
    remainingRepaymentMonths: 60,
    paymentHistory: "Delayed",
    activeRequest: true,
    salaryCertificateAmount: 16000,
    salaryCertificateExpired: false,
    documentConfidence: 89,
    hasCompanyLetterhead: true,
    hasAuthorizedSignature: true,
    employeeDetailsMatch: true,
    averageSalaryTransfer6Months: 16000,
    hasMedicalDocument: true,
    medicalProviderRecognized: true,
    medicalQRVerified: true,
    medicalDateValid: true,
    supportingCircumstance: "Temporary hardship / medical treatment / income loss",
  },
  "CASE-D": {
    caseId: "CASE-D",
    beneficiaryName: "Omar Al Suwaidi",
    beneficiaryId: "BEN-784-004",
    emiratesId: "784-1982-1122334-5",
    loanId: "LOAN-2020-044",
    monthlyIncome: 20000,
    financialObligations: 5000,
    familyMembers: 4,
    originalLoanAmount: 800000,
    remainingLoanBalance: 400000,
    arrearsAmount: 15000,
    unpaidInstallments: 3,
    currentInstallment: 2500,
    remainingRepaymentMonths: 80,
    paymentHistory: "Irregular",
    activeRequest: true,
    salaryCertificateAmount: 20000,
    salaryCertificateExpired: false,
    documentConfidence: 95,
    hasCompanyLetterhead: true,
    hasAuthorizedSignature: true,
    employeeDetailsMatch: true,
    averageSalaryTransfer6Months: 20000,
    hasMedicalDocument: false,
  },
  "CASE-E": {
    caseId: "CASE-E",
    beneficiaryName: "Fatima Al Ali",
    beneficiaryId: "BEN-784-005",
    emiratesId: "784-1988-5566778-9",
    loanId: "LOAN-2019-090",
    monthlyIncome: 0,
    financialObligations: 2000,
    familyMembers: 5,
    originalLoanAmount: 600000,
    remainingLoanBalance: 300000,
    arrearsAmount: 20000,
    unpaidInstallments: 6,
    currentInstallment: 3000,
    remainingRepaymentMonths: 60,
    paymentHistory: "Irregular",
    activeRequest: false,
    salaryCertificateAmount: 0,
    salaryCertificateExpired: false,
    documentConfidence: 80,
    hasCompanyLetterhead: false,
    hasAuthorizedSignature: false,
    employeeDetailsMatch: true,
    averageSalaryTransfer6Months: 0,
    hasMedicalDocument: false,
    supportingCircumstance: "Unemployment / income loss",
  }
};
